jobs:
  lint-multi-os:
    name: Lint ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v3
        with:
          key: v0-${{ runner.os }}-pip-lint-${{ hashFiles('setup.py') }}
          path: ~/.cache/pip
          restore-keys: |
            v0-${{ runner.os }}-pip-lint-
            v0-${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install .[lint]
      - name: Run pre-commit hooks
        uses: pre-commit/action@v2.0.3
    strategy:
      matrix:
        os: [ macOS-latest, ubuntu-latest, windows-latest ]
name: CI
on: [ pull_request, push ]
permissions: read-all
